# Generated by Django 4.2.4 on 2023-09-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовка')),
                ('description', models.TextField(max_length='Описание')),
                ('is_completed', models.BooleanField(verbose_name='Выполнена')),
                ('created_at', models.BooleanField(verbose_name='Создана')),
                ('image', models.ImageField(upload_to=True, verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Таск',
                'verbose_name_plural': 'Таски',
            },
        ),
    ]
